Fantastix/config/routes.rb
Fantastix::Application.routes.draw do

 devise_for :accounts

root to: "static_pages#home"

match 'about', to: 'static_pages#about' , via: :get
match 'contact', to: 'static_pages#contact' , via: :get

 
  resources :account_groups

  resources :posts

  resources :groups

  resources :accounts

  

end

Fantastix/app/models/account_group.rb
class AccountGroup < ActiveRecord::Base
	belongs_to :account
    belongs_to :group
end

Fantastix/app/controllers/account_groups_controller.rb
class AccountGroupsController < ApplicationController
  before_action :set_account_group, only: [:show, :edit, :update, :destroy]

  # GET /account_groups
  # GET /account_groups.json
  def index
    @account_groups = AccountGroup.all
  end

  # GET /account_groups/1
  # GET /account_groups/1.json
  def show
  end

  # GET /account_groups/new
  def new
    @account_group = AccountGroup.new
  end

  # GET /account_groups/1/edit
  def edit
  end

  # POST /account_groups
  # POST /account_groups.json
  def create
    @account_group = AccountGroup.new(account_group_params)

    respond_to do |format|
      if @account_group.save
        format.html { redirect_to @account_group, notice: 'Account group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @account_group }
      else
        format.html { render action: 'new' }
        format.json { render json: @account_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_groups/1
  # PATCH/PUT /account_groups/1.json
  def update
    respond_to do |format|
      if @account_group.update(account_group_params)
        format.html { redirect_to @account_group, notice: 'Account group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_groups/1
  # DELETE /account_groups/1.json
  def destroy
    @account_group.destroy
    respond_to do |format|
      format.html { redirect_to account_groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_group
      @account_group = AccountGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_group_params
      params.require(:account_group).permit(:account_id, :group_id)
    end
end

Fantastix/app/helpers/account_groups_helper.rb
module AccountGroupsHelper
end

Fantastix/app/views/account_groups/_form.html.erb
<%= form_for(@account_group) do |f| %>
  <% if @account_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account_group.errors.count, "error") %> prohibited this account_group from being saved:</h2>

      <ul>
      <% @account_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.number_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Fantastix/app/views/account_groups/edit.html.erb
<h1>Editing account_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @account_group %> |
<%= link_to 'Back', account_groups_path %>

Fantastix/app/views/account_groups/index.html.erb
<h1>Listing account_groups</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Group</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @account_groups.each do |account_group| %>
      <tr>
        <td><%= account_group.account_id %></td>
        <td><%= account_group.group_id %></td>
        <td><%= link_to 'Show', account_group %></td>
        <td><%= link_to 'Edit', edit_account_group_path(account_group) %></td>
        <td><%= link_to 'Destroy', account_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account group', new_account_group_path %>

Fantastix/app/views/account_groups/new.html.erb
<h1>New account_group</h1>

<%= render 'form' %>

<%= link_to 'Back', account_groups_path %>

Fantastix/app/views/account_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @account_group.account_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @account_group.group_id %>
</p>

<%= link_to 'Edit', edit_account_group_path(@account_group) %> |
<%= link_to 'Back', account_groups_path %>